POST   http://localhost:3000/new-user
Content-Type: application/json

{
  "username": "  sdgsdgd",
  "password": 123
}

### 
POST   http://localhost:3000/login-user
Content-Type: application/json

{
  "username": "Kyle"
}